# Generated by Django 4.0.6 on 2022-07-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
